# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 10:26
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euser',
            name='one_c_id',
        ),
        migrations.AddField(
            model_name='euser',
            name='alias_id',
            field=models.UUIDField(auto_created=True, default='00000000-0000-0000-0000-000000000000'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='день рождения'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='администратор'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
